---

name: CI (Main branch)
on:
  push:
    branches: [main]
jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm-release:
    uses: naviteq/github-actions/.github/workflows/create-helm-release.yaml@main
    needs: [docker]
    with:
      CHART_LOCATION: helm
      UPDATE_BRANCH: main

  helm:
    name: Build Helm chart
    runs-on: ubuntu-latest
    needs: [helm-release]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Build
        run: |
          cd helm
          helm lint .
          helm package .

  release:
    uses: naviteq/github-actions/.github/workflows/create-release.yaml@main
    secrets: inherit
    needs: [helm]
