---

name: CI (Main branch)
on:
  push:
    branches: [main]
jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@nr-71/docker-build-rework
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
      DOCKER_PLATFORMS: linux/amd64,linux/arm64
      BUILD_ARGS: |
        TEST_MODE=true
        APP_ENV=ci
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_SECRETS: |
        smoke_secret=plain-text-value

  #helm:
  #  uses: naviteq/github-actions/.github/workflows/helm-release.yaml@main
  #  needs: [docker]
  #  with:
  #   CHART_LOCATION: helm
  #  secrets:
  #    TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #release:
  #  uses: naviteq/github-actions/.github/workflows/create-release.yaml@main
  #  secrets: inherit
  #  needs: [helm]
