---

name: Pull request code validation and building (Main branch)
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Python format
        run: uv run black --check .

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      opensearch:
        image: opensearchproject/opensearch
        ports:
          - 9200:9200
          - 9600:9600
        env:
          discovery.type: single-node
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Tests run
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          max_attempts: 3
          command: uv run python test/run_tests.py unit

  version:
    name: Update version 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/update-version
        with:
          version: pr

  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    needs: [version, format, unit-test]
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [docker]
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
      options: --entrypoint /bin/sh
    steps:
      - run: /curator/curator --version

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release-github.yaml@main
    needs: [docker]
    with:
      chart_path: helm
      ghcr_repo: ${{ github.repository }}
      bump_version_in_git: false
    secrets:
      GITHUB_APP_ID: ${{ secrets.NAVITEQ_GITHUB_APP_ID }}
      GITHUB_APP_KEY: ${{ secrets.NAVITEQ_GITHUB_APP_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
