---

name: Pull request code validation and building (Main branch)
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Python format
        uses: psf/black@stable
        with:
          version: 23.1.0

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      opensearch:
        image: opensearchproject/opensearch
        ports:
          - 9200:9200
          - 9600:9600
        env:
          discovery.type: single-node
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - uses: syphar/restore-pip-download-cache@v1
      - run: pip install -r requirements-dev.txt
      - name: Tests run
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 3
          command: python test/run_tests.py unit

  version:
    name: Update version 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update-version
        with:
          version: pr

  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    needs: [version, format, unit-test]
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [docker]
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
      options: --entrypoint /bin/sh
    steps:
      - run: /curator/curator --version

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release.yaml@main
    needs: [test]
    with:
      CHART_LOCATION: helm
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
