---
name: Curator release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
