---
name: Curator release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    name: Build Helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Build
        run: |
          cd helm
          helm lint .
          helm package .
