---
name: Curator release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  version:
    name: Update version 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/update-version
        with:
          version: tag

  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    needs: [version]
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release.yaml@main
    needs: [docker]
    with:
      CHART_LOCATION: helm
      PUSH_TO_GITHUB: true
      UPDATE_BRANCH: main
    secrets:
      TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
