on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Python format
        uses: psf/black@stable
        with:
          version: 22.6.0

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt
      - uses: syphar/restore-pip-download-cache@v1
      - run: pip install -r requirements.txt
      - run: pip install nose mock
      - name: Tests run
        run: python test/run_tests.py unit

  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    needs: [format, unit-test]
    with:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
